#pragma once

#include "sdkconfig.h"

#define FACTORY_BOARD_WIDTH 1440
#define FACTORY_BOARD_HEIGHT 720
#define FACTORY_DRAW_BUF_LINES 40
#define FACTORY_I2C_FREQ_HZ 400000
#define FACTORY_PANEL_SPI_CLOCK_HZ 40000000

#define FACTORY_EPD_PARTIAL_PASSES 7
#define FACTORY_EPD_FULL_PASSES 5

#define FACTORY_TOUCH_I2C_SDA CONFIG_FACTORY_TOUCH_I2C_SDA
#define FACTORY_TOUCH_I2C_SCL CONFIG_FACTORY_TOUCH_I2C_SCL
#define FACTORY_TOUCH_INT_GPIO CONFIG_FACTORY_TOUCH_INT_GPIO

#define FACTORY_PCA_T_RST 0
#define FACTORY_PCA_CC_SW0 1
#define FACTORY_PCA_CC_SW1 2
#define FACTORY_PCA_LR_RST 3
#define FACTORY_PCA_NRF_CE 4
#define FACTORY_PCA_SHUTDOWN 5
#define FACTORY_PCA_HDMI_RST 6
#define FACTORY_PCA_HDMI_EN 7
#define FACTORY_PCA_EP_OE 8
#define FACTORY_PCA_EP_MODE 9
#define FACTORY_PCA_1V8_EN 10
#define FACTORY_PCA_TPS_PWRUP 11
#define FACTORY_PCA_VCOM_CTRL 12
#define FACTORY_PCA_TPS_WAKEUP 13
#define FACTORY_PCA_TPS_PWR_GOOD 14
#define FACTORY_PCA_TPS_INT 15

#define FACTORY_EXTIO_PIN_BASE 0x1000U
#define FACTORY_EXTIO_PIN(pin) (FACTORY_EXTIO_PIN_BASE + (pin))
