; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;********************************************
;             select a example 
;********************************************

; src_dir = examples/c6_wifi_scan

; src_dir = examples/es8311/microphone_speak      ;
; src_dir = examples/es8311/playFromSD            ;
; src_dir = examples/es8311/playFromSDCard        ;

; src_dir = examples/FastEPD/gif_player         ;
; src_dir = examples/FastEPD/grayscale_test     ;
; src_dir = examples/FastEPD/show_jpeg          ;

; src_dir = examples/spiffs
; src_dir = examples/i2c_scan

; src_dir = examples/lvgl_benchmark               ;
src_dir = examples/lvgl_demo
; src_dir = examples/lvgl_draw                  ;
; src_dir = examples/lvgl_draw_gt911           ;

; src_dir = examples/HardwareTest/src
; src_dir = examples/sd_card
; src_dir = examples/XL9555/read
; src_dir = examples/XL9555/write

; src_dir = examples/touch_gt911

;----------------------------------------------;
; boards_dir = boards
[env:esp32-p4-evboard]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = esp32-p4-evboard
framework = arduino
upload_speed =  921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = default_16MB.csv
board_build.flash_mode = dio
custom_include_path_length_threshold = 30000

build_flags =
    -Wno-unused-variable
    -Wno-unused-parameter
    -Wno-missing-field-initializers
    -Wno-sign-compare
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DCONFIG_ESP_WIFI_REMOTE_ENABLED=1


    -DCORE_DEBUG_LEVEL=3

    ; ; Debug output
    ; -DCORE_DEBUG_LEVEL=3
    ; 
;     -DBOARD_HAS_PSRAM
    ; -DPSRAM_SPEED=120MHz

;     ; Enable -DARDUINO_USB_CDC_ON_BOOT will start printing and wait for terminal access during startup
;     -DARDUINO_USB_CDC_ON_BOOT=1

;     -DCORE_DEBUG_LEVEL=5

;     ; -DLOG_PORT=Serial


;     -Wl,--gc-sections

; lib_deps =
;     ; lvgl/lvgl@8.4.0
;     ; lewisxhe/SensorLib@0.2.2
;     ; lewisxhe/XPowersLib@^0.2.7
;     Wire
;     SPI


