; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;--------------- select a example --------------;
; src_dir = examples/lvgl_test/main             ;
src_dir = examples/UI_demo             ;


;******************************************************
; Example routines using the FastEPD library
;******************************************************
; src_dir = examples/FastEPD/gif_player         ;
; src_dir = examples/FastEPD/grayscale_test     ;
; src_dir = examples/FastEPD/show_jpeg          ;

;----------------------------------------------;
; boards_dir = boards
[env:esp32-p4-evboard]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = esp32-p4-evboard
framework = arduino
upload_speed =  921600
monitor_speed = 115200
; monitor_port = COM136
monitor_filters = esp32_exception_decoder
board_build.partitions = default_16MB.csv
; board_upload.maximum_size = 8388608
; board_build.partitions = partitions_16m_no_ota.csv

; extra_scripts =  ./script/pos_extra_script.py

; build_flags = 
;     -DBOARD_HAS_PSRAM
    ; -DPSRAM_SPEED=120MHz

;     ; Enable -DARDUINO_USB_CDC_ON_BOOT will start printing and wait for terminal access during startup
;     -DARDUINO_USB_CDC_ON_BOOT=1

;     -DCORE_DEBUG_LEVEL=5

;     ; -DLOG_PORT=Serial

;     -DDISABLE_ALL_LIBRARY_WARNINGS

;     -Wl,--gc-sections

; lib_deps =
;     ; lvgl/lvgl@8.4.0
;     ; lewisxhe/SensorLib@0.2.2
;     ; lewisxhe/XPowersLib@^0.2.7
;     Wire
;     SPI
