idf_component_register(
    SRCS
        "platform/Arduino.cpp"
        "platform/HalDisplay.cpp"
        "platform/HalStorage.cpp"
        "platform/HardwareSerial.cpp"
        "Logging/Logging.cpp"
        "FsHelpers/FsHelpers.cpp"
        "InflateReader/InflateReader.cpp"
        "ZipFile/ZipFile.cpp"
        "Utf8/Utf8.cpp"
        "EpdFont/EpdFont.cpp"
        "EpdFont/EpdFontFamily.cpp"
        "EpdFont/FontDecompressor.cpp"
        "GfxRenderer/Bitmap.cpp"
        "GfxRenderer/BitmapHelpers.cpp"
        "GfxRenderer/FontCacheManager.cpp"
        "GfxRenderer/GfxRenderer.cpp"
        "Txt/Txt.cpp"
        "Epub/Epub.cpp"
        "Epub/Epub/BookMetadataCache.cpp"
        "Epub/Epub/Page.cpp"
        "Epub/Epub/ParsedText.cpp"
        "Epub/Epub/Section.cpp"
        "Epub/Epub/htmlEntities.cpp"
        "Epub/Epub/blocks/ImageBlock.cpp"
        "Epub/Epub/blocks/TextBlock.cpp"
        "Epub/Epub/converters/ImageDecoderFactory.cpp"
        "Epub/Epub/converters/ImageToFramebufferDecoder.cpp"
        "Epub/Epub/css/CssParser.cpp"
        "Epub/Epub/hyphenation/HyphenationCommon.cpp"
        "Epub/Epub/hyphenation/Hyphenator.cpp"
        "Epub/Epub/hyphenation/LanguageRegistry.cpp"
        "Epub/Epub/hyphenation/LiangHyphenation.cpp"
        "Epub/Epub/parsers/ChapterHtmlSlimParser.cpp"
        "Epub/Epub/parsers/ContainerParser.cpp"
        "Epub/Epub/parsers/ContentOpfParser.cpp"
        "Epub/Epub/parsers/TocNavParser.cpp"
        "Epub/Epub/parsers/TocNcxParser.cpp"
        "expat/xmlparse.c"
        "expat/xmlrole.c"
        "expat/xmltok.c"
        "uzlib/src/tinflate.c"
    INCLUDE_DIRS
        "platform"
        "Logging"
        "FsHelpers"
        "InflateReader"
        "ZipFile"
        "Utf8"
        "Serialization"
        "EpdFont"
        "GfxRenderer"
        "Txt"
        "Epub"
        "Epub/Epub"
        "Epub/Epub/blocks"
        "Epub/Epub/converters"
        "Epub/Epub/css"
        "Epub/Epub/hyphenation"
        "Epub/Epub/parsers"
        "XmlParserUtils"
        "expat"
        "uzlib/src"
    REQUIRES
        esp_timer
        freertos
        heap
        log
        fastepd
)

target_compile_definitions(${COMPONENT_LIB} PRIVATE
    LOG_LEVEL=1
    XML_GE=1
    XML_CONTEXT_BYTES=1024
)

target_compile_options(${COMPONENT_LIB} PRIVATE
    -Wno-format
    -Wno-missing-field-initializers
    -Wno-missing-braces
    -Wno-sign-compare
    -Wno-unused-function
    -Wno-unused-parameter
    -Wno-unused-variable
)
